### ISSUE TITLE
메인, 로그인, 회원가입 페이지 css 수정 및 애니메이션 생성

### ISSUE THREAD

**Issue by dawncoding** [Stendhalsynd/career-up-front#115]
## Description
메인, 로그인, 회원가입 페이지 css 수정 및 애니메이션 생성

## Todo
- [ ] 메인페이지 스크롤 인터렉션 적용
- [ ] 메인페이지 재직자 리스트 자동 스크롤 구현
- [ ] 로그인 페이지 css 수정, 애니메이션 적용
- [ ] 회원가입 페이지 css 수정, 애니메이션 적용

## ETC
기타사항

## References
- [참고자료](링크)
