### ISSUE TITLE
재직자 자기소개 , 상세 정보, 채팅방 목록 애니메이션 추가

### ISSUE THREAD

**Issue by suhyuns22** [Stendhalsynd/career-up-front#116]
## Description
애니메이션 추가

## Todo
- [x] 재직자 자기소개 애니메이션
- [x] 재직자 상세정보 애니메이션
- [x] 채팅방 목록 애니메이션

## ETC
기타사항

## References
- [참고자료](링크)
