### ISSUE TITLE
Storybook viewport 추가

### ISSUE THREAD

**Issue by Stendhalsynd** [Stendhalsynd/career-up-front#21]
## Description
이제 storybook 에서 viewport 를 설정할 수 있게 되었습니다.
매번 개발자모드로 불편하게 크기조절하지 마시고 편리하게 반응형 작동여부를 확인하세요~!

## Todo
- [x] storybook viewport 설정
![](https://velog.velcdn.com/images/qmflf556/post/3dda590d-abe0-419d-90c3-b66bab2cb9cd/image.png)
  - 이제 반응형 여부를 storybook 상단의 viewport 설정을 통해 편하게 확인하세요 🤗

- [x] @dawncoding @syxxne 변경사항 알림
  - 이제 Box 컴포넌트의 모든 Space 는 string 으로 전환했습니다. marginTop = {1} 이 아니라 padding = {'10vw'} 같은 방식으로 전환되었습니다.
  - Box 컴포넌트에 maxWidth, maxHeight 를 추가했습니다. 이 모든 변경사항은 Flex, Grid 컴포넌트에 같이 적용됩니다. (두 컴포넌트는 Box 컴포넌트를 상속받았습니다.)

- [x] 2개이상의 파일이 있는 모든 디렉토리의 경로는 index.ts 라는 파일이 관리합니다.
  ![](https://velog.velcdn.com/images/qmflf556/post/3e40db87-812d-4b36-84c7-28af110cbeae/image.png)
  > 변경 이후 import 부분의 변화를 보시면 왜 이방식을 추천하는지 이해하실 수 있을 것 같습니다 👍

## 참고할만한 좋은 문법

`interface 상속 및 추가`

```ts
interface Animal {
	age: number;
  	name: string;
}

interface Dog extends Animal {
	sound: string;
}

```

`Type 상속 및 추가`

```

type Animal = {
	age: number;
    name: string;
}

type Dog = Animal & {
	sound: string;
}

```

`Type 상속시 특정 프로퍼티 제거`

```

type Animal = {
	age: number;
    name: string;
    variant: string;
}

type Dog = Animal & {
	sound: string;
}

type Cat = Omit<Dog, 'variant'>;

```
