### ISSUE TITLE
layout 컴포넌트 생성

### ISSUE THREAD

**Issue by Stendhalsynd** [Stendhalsynd/career-up-front#4]
## Description
레이아웃에 해당하는 Box, Flex, Grid 컴포넌트 생성

## Todo
- [ ] Box 컴포넌트 생성
- [ ] Flex 컴포넌트 생성
- [ ] Grid 컴포넌트 생성

## ETC
- [ ] TODO : tsconfig.json, tailwincss 설정파일, SSR RootLayout 및 StyledComponent ThemeProvider 문제 해결 

## References
- [custom storybook control 설정](https://thoughtbot.com/blog/creating-a-custom-color-control-in-storybook)
- [warning className did not match 오류](https://tesseractjh.tistory.com/164)
- [warning className did not match 오류](https://blog.shift.moe/2021/01/02/prop-classname-did-not-match/)
- [warning className did not match 오류](https://nextjs.org/docs/architecture/nextjs-compiler#styled-components)
- [warning className did not match 오류](https://github.com/vercel/app-playground/tree/main/app/styling/styled-components)
- [Vercel - Cannot find module '파일명' or its corresponding type declarations 오류](https://velog.io/@shyuuuuni/Vercel-Cannot-find-module-%ED%8C%8C%EC%9D%BC%EB%AA%85-or-its-corresponding-type-declarations-%EC%98%A4%EB%A5%98-%ED%95%B4%EA%B2%B0)
- [Already included file name differs from file name only in casing... 이슈](https://choiblog.tistory.com/125)
- [Already included file name differs from file name only in casing... 이슈](https://velog.io/@a770418/vercel%EC%97%90-%EA%B3%84%EC%86%8D-Already-included-file-name-differs-from-file-name-only-in-casing-%EC%98%A4%EB%A5%98%EA%B0%80-%EC%83%9D%EA%B8%B0%EB%8A%94-%EB%AC%B8%EC%A0%9C)
