### ISSUE TITLE
WorkerMyPage 페이지 생성

### ISSUE THREAD

**Issue by Stendhalsynd** [Stendhalsynd/career-up-front#59]
## Description
WorkerMyPage 페이지 생성

## Todo
- [x] MyPage 템플릿 활용
- [x] 반응형 적용
- [x] chromatic storybook 배포
- [x] Font-Family 추가
  - Noto Sans, Notable 폰트체 추가
- [x] Text variant 에 font-weight 추가
  - 현재 커리업 프로젝트에 사용되는 Typo 는 noto sans 16 ~ 40 medium 과 bold  , Notable 이나 현재의 Text 컴포넌트의 variant 는 fontSize, letterSpacing, lineHeight 만 변경합니다. 
  - 그래서 variant 하나만 적용해도 fontSize, fontWeight, letterSpaicng, lineHeight 가 적용되도록 수정했습니다.
- [x] Box 컴포넌트에 box-sizing 추가 및 기본값으로 border-box 설정 -> 이부분이 설정되어 있지 않아서 localhost 와 storybook 상에 스타일이 다르게 나타나는 이슈가 있었습니다.
- [x] Button 컴포넌트 모든 스토리북 추가
 
<img width="954" alt="스크린샷 2023-11-26 오전 10 07 43" src="https://github.com/Stendhalsynd/career-up-front/assets/96957774/71128f8d-dc84-4f59-9b47-5d0015580ebf">

- box-sizing 설정을 하지 않았을때 `좌: 스토리북, 우: localhost`

<img width="874" alt="스크린샷 2023-11-26 오전 10 08 33" src="https://github.com/Stendhalsynd/career-up-front/assets/96957774/c1fbe8f7-9295-4440-85d5-34d737e682c0">

- box-sizing 설정을 한 후, 좌우가 동일하게 보인다.

### 폰트체 적용 방법

현재 RootLayout 에 Noto Sans 를 전역적으로 사용하도록 해두었으니 Notable 을 쓰는 곳에서만 해당 방법을 가져다 쓰시면 됩니다.

현재 폰트체는 utils/styles.ts 에서notoSansKr, notable 이라는 변수로 export 를 해두었습니다.
사용법은 아래와 같은 내용을 Text 에 TypeDoc 으로 추가해두었습니다. 마우스 호버하시면 보실 수 있습니다.

```ts

import { notable, notoSansKr } from 'styles/fonts/ts'

<Text className={notoSansKr.className} >notoSans 예시</Text >
<Text className={notable.className} >notable 예시</Text >

```

### Text 변경 Detail

`variant 종류`

```ts
export type TextVariant =
  | 'xxSmall'
  | 'xSmall'
  | 'extraSmall'
  | 'small'
  | 'medium'
  | 'mediumLarge'
  | 'large'
  | 'xxSmallBold'
  | 'xSmallBold'
  | 'extraSmallBold'
  | 'smallBold'
  | 'mediumBold'
  | 'mediumLargeBold'
  | 'largeBold'
```

`varint, fontSize` 가 각각 몇 px 을 나타내는지 매번 보는게 번거로워서 각각의 type 프로퍼티 위에 TypeDoc 을 추가해두었으니 이제 다음과 같이 fontSize, variant 위에 마우스를 호버시키면 세부사항을 확인할 수 있습니다.

![스크린샷 2023-11-26 오전 5 04 40](https://github.com/Stendhalsynd/career-up-front/assets/96957774/d5c1eaf8-bb06-4e3f-9ccd-1de2045bee21)

> 참고로 fontWeight 는 variant 에 Bold 를 뒤에 붙이면 700, 안붙이면 500 입니다. `large` <-> `largeBold`

### 설치한 애드온

```
npm i -D @storybook/addon-themes
```

## References
- [지성현 - Font Optimization](https://anhyang.tistory.com/120)
- [J4J Next13 새로운 기능 알아보기](https://jforj.tistory.com/338)
- [NextJS Font Docs](https://nextjs.org/docs/app/building-your-application/optimizing/fonts)
- [storybook docs - 앞으로 storybook 7.x 이후로는 뉴비들의 진입장벽을 낮추기 위해 style 설정을 자동으로 해주겠다. 그러니 관련 에드온을 따로 설정할 필요가 없다.. 는 글](https://storybook.js.org/blog/zero-config-support-for-tailwind-mui-styled-components-and-emotion/)
