### ISSUE TITLE
Header 컴포넌트 생성

### ISSUE THREAD

**Issue by dawncoding** [Stendhalsynd/career-up-front#6]
## Description
Header 컴포넌트 생성

## Todo
- [x] icon component 생성
- [x] logo image component 생성
- [ ] header presentation component 생성
- [ ] header container component 생성
- [ ] mod: logo, icon component 반응형 웹 구현
- [ ] mod: icon component width, height defaultValue 설정
width, height을 입력하지 않아도 컴포넌트 사용할 수 있도록 하기

## ETC
기타사항

## References
- [참고자료](링크)
